version: "3"
services:
  db:
    build: ./db
    ports:
      - "3306:3306"
    volumes:
      - ./db/database:/var/lib/mysql
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    #   MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  web:
    build: ./apache
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: wordpress
      DB_PASSWORD: wordpress
#